name: Build and Test

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review, review_requested, review_request_removed ]

  schedule:
    - cron: "00 09 * * *"  # Run at 9:00 AM every day

permissions: read-all

jobs:
  build-and-link-check:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PortAudio dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev python3-all-dev
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Clone typescript_sdk
        run: git clone https://github.com/strands-agents/sdk-typescript ./sdk-typescript

      - name: Install dependencies
        run: |
          pip install .
          npm install ./sdk-typescript
          npm install
      - name: Build docs
        run: |
          mkdocs build --clean
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Check links with lychee
        id: lychee
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0
        with:
          args: '--offline --root-dir "$(pwd)" --cache --max-cache-age 1d .'
          workingDirectory: './site'

