name: Typecheck files

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, review_requested, review_request_removed ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clone typescript_sdk
        run:  git clone https://github.com/strands-agents/sdk-typescript.git/ ./sdk-typescript

      - name: Install SDK
        run:  npm install ./sdk-typescript

      - name: Run tests
        run: npm run test
